version: "3"
services:
  app-container:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./local.env
    environment:
      - PORT=3000